version: '3.8'

volumes:
  hyperespace-data:
    driver: local

networks:
  hyperespace-network:
    driver: bridge

services:

  nginx:
    build:
      args:
        VERSION: $NGINX_VERSION
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      target: dev
    depends_on:
      - php
    volumes:
      - ./public:/hyperespace/public
    ports:
      - "${NGINX_PORT}:80"
    restart: always
    networks:
      - hyperespace-network

  php:
    build:
      args:
        VERSION: $PHP_VERSION
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: dev
    volumes:
      - .:/hyperespace
    depends_on:
      - postgres
    restart: always
    networks:
      - hyperespace-network

  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - hyperespace-data:/var/lib/postgresql/data
    restart: always
    networks:
      - hyperespace-network

  adminer:
    image: adminer:4.8.1
    restart: always
    profiles:
      - "dev"
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - hyperespace-network


